- Dockerfile
- Dockerfile.aarch64
This PR adds the `MACHINE_LEARNING_ENABLED` [introduced by the immich team](https://github.com/immich-app/immich/commit/bdad18a572867fca7499d9f73084b20456bc60d2)
> fix: disable properly machine-learning

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
mentioned here: https://github.com/imagegenius/docker-immich/issues/12#issuecomment-1401168784
> fix: .reverse-geocoding-dump permissions

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
copies modifications from https://github.com/immich-app/immich/pull/1523
> reduce image size (noml)

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
copies modifications from https://github.com/immich-app/immich/pull/1523
> reduce image size

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
Use Immich environment variables instead of editing hosts file. `PUBLIC_IMMICH_SERVER` is not in their env.example but used for web to fetch data.
> use env from immich instead of hosts file

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
> fix: use env from immich instead of hosts file for noml

- root/defaults/nginx.conf
> fix: update nginx.conf for noml

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
- root/etc/s6-overlay/s6-rc.d/svc-typesense/run
- root/etc/s6-overlay/s6-rc.d/svc-typesense/type
Add typesense support for noml.
> feat: prepare for typesense

- root/etc/s6-overlay/s6-rc.d/svc-machine-learning/run
Quick fix for https://github.com/imagegenius/docker-immich/issues/39
> fix: HOME env #39

- root/defaults/default.site
- root/defaults/nginx.conf
matches upstream nginx configs
> feat: update nginx configs (main)

- root/defaults/default.site
- root/defaults/nginx.conf
matches upstream nginx configs
> feat: update nginx configs (noml)

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
- root/etc/s6-overlay/s6-rc.d/svc-typesense/run
- root/etc/s6-overlay/s6-rc.d/svc-typesense/type
running ml in the noml image defeats its purpose, also requires AVX
> feat: remove typesense (noml)

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
> fix: copy gunicorn.conf.py

- root/defaults/default.site
Matches [latest nginx changes](https://github.com/immich-app/immich/pull/2246)
> feat: sync upsteam nginx.conf (main)

- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/svc-machine-learning/run
- root/etc/s6-overlay/s6-rc.d/svc-server/run
- root/etc/s6-overlay/s6-rc.d/svc-typesense/run
Prevent starting typesense and machine-learning based on env `TYPESENSE_ENABLED` and `IMMICH_MACHINE_LEARNING_URL`
> feat: disable typesense and ml with env (main)

- root/defaults/migrate.py
> fix: migrate profileimage (main)

- Jenkinsfile
- jenkins-vars.yml
- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-check-variables/run
> feat: remove unused `JWT_SECRET` (noml)

- Dockerfile
- Dockerfile.aarch64
- root/etc/s6-overlay/s6-rc.d/svc-machine-learning/run
Hotfix for [v1.55](https://github.com/immich-app/immich/releases/tag/v1.55.0)
> fix: move from flask to fastapi

- Dockerfile
- Dockerfile.aarch64
- jenkins-vars.yml
- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
- root/etc/s6-overlay/s6-rc.d/svc-machine-learning/run
Face recognition implementation.
> feat: facial recognition

- Dockerfile
- Dockerfile.aarch64
https://github.com/immich-app/immich/pull/2430 has been merged and will be released for v1.56.1 / 1.57
> chore: update heif package (noml)

- Dockerfile
- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
The migration script has been there for a month, we can remove it.
> feat: remove migration script (main)

- Dockerfile
- Dockerfile.aarch64
fix v1.56.1 there is still issues with heic files. @hydazz  can be merged
> chore: fix v1.56.1

- readme-vars.yml
- root/defaults/main.py
- root/etc/s6-overlay/s6-rc.d/init-config-cuda/run
- root/etc/s6-overlay/s6-rc.d/svc-machine-learning/run
Change env to enable the machine-learning with gpu from `ML_CUDA` TO `CUDA_ACCELERATION` and add a note in the README
> fix: change env to enable cuda acceleration

- Dockerfile
- Dockerfile.aarch64
- root/etc/s6-overlay/s6-rc.d/init-config-cuda/run
Onnxruntime v1.15 is released and compatible with python 3.11
> feat: revert onnxruntime to stable

- Dockerfile
- Dockerfile.aarch64
- root/defaults/migrate.py
- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
Replace the symbolic link which links the two `./upload` folders with /photos by the environment variable `IMMICH_MEDIA_LOCATION`
> feat: replace `ln` with an environment variable to set the /photos folder (noml)

- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/svc-machine-learning/run
- root/etc/s6-overlay/s6-rc.d/svc-typesense/run
Disable machine learning if `IMMICH_MACHINE_LEARNING_URL`is different from `http://127.0.0.1:3003`
> feat: support cuda node

- Dockerfile
- Dockerfile.aarch64
- root/etc/s6-overlay/s6-rc.d/svc-microservices/run
- root/etc/s6-overlay/s6-rc.d/svc-server/run
- root/usr/local/bin/immich
Add packages to support raw images and edit entrypoints
> feat: prepare for v1.61 (noml)

- Dockerfile.aarch64
- jenkins-vars.yml
Revert changes I made in #97 for aarch64
> fix: aarch64

- Dockerfile
- Dockerfile.aarch64
- root/etc/s6-overlay/s6-rc.d/init-config-cuda/run
- root/etc/s6-overlay/s6-rc.d/svc-machine-learning/run
- root/etc/s6-overlay/s6-rc.d/svc-typesense/run
This PR aims to support poetry and update typesense from `24.0` to `24.1`
Edit: Raw images support will come in another PR, later
> feat: use poetry

- root/etc/s6-overlay/s6-rc.d/svc-machine-learning/run
Hotfix for v1.64.0 (machine learning does not start)
> hotfix: v1.64.0 (main)

- Dockerfile
- Dockerfile.aarch64
> fix: cli install (noml)

- Dockerfile
- Dockerfile.aarch64
cleaner install of cli with `--prefix`
> fix: cli install (main)

- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
- root/etc/s6-overlay/s6-rc.d/svc-microservices/run
- root/etc/s6-overlay/s6-rc.d/svc-server/run
> fix: disable typesense (noml)

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
Update docs and provide a little fix mentionned [here](https://github.com/imagegenius/docker-immich/pull/136#issuecomment-1629168594)
> chore: update docs

- readme-vars.yml
> fix: generate templates

- Dockerfile
- Dockerfile.aarch64
> fix: keep libltdl

- Dockerfile
- Dockerfile.aarch64
quick fix for [this issue](https://github.com/immich-app/immich/issues/3227)
> fix: add missing package (libexif)

- root/etc/s6-overlay/s6-rc.d/init-check-variables/run
> feat: support redis socket (main)

- root/etc/s6-overlay/s6-rc.d/init-check-variables/run
See #154. Also support `DB_URL` which was already supported in main
> feat: support redis socket (noml)

- root/etc/s6-overlay/s6-rc.d/init-check-variables/run
> fix: check if redis_socket or redis_url are set (noml)

- root/usr/local/bin/immich-admin
> fix: admin-cli (noml)

- root/usr/local/bin/immich-admin
> fix: admin-cli (main)

- Dockerfile
- Dockerfile.aarch64
See https://github.com/immich-app/immich/pull/3655
> fix: libvips without tiff (main)

- Dockerfile
- Dockerfile.aarch64
Possible fix for  #152.
Use ffmpeg from jellyfin repo
> fix: ffmpeg (main)

- Dockerfile
- Dockerfile.aarch64
- root/etc/s6-overlay/s6-rc.d/svc-server/run
v1.75 introduces new breaking changes.
> fix: update to 1.75 (main)

- Dockerfile
- Dockerfile.aarch64
> fix: update to 1.75 (noml)

- Dockerfile
- Dockerfile.aarch64
This PR fixes the white balance for raw images like upstream images https://github.com/immich-app/immich/pull/3806
> fix: imagemagick (main)

- Dockerfile
- Dockerfile.aarch64
- root/etc/s6-overlay/s6-rc.d/svc-machine-learning/run
See https://github.com/immich-app/immich/pull/3934
> fix(v1.77)!: machine-learning (main)

- Dockerfile
- Dockerfile.aarch64
> fix: add log_conf.json (main)

- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/svc-machine-learning/run
Increasing timeout of worker for this: https://github.com/imagegenius/docker-immich/issues/181
Closes #181 
fix is based on original repo fix of https://github.com/immich-app/immich/commit/f5826c8e9ae0c18032ff4d3a039c7325a4dccd92
> Increasing timeout for machine learning workers

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
- root/etc/s6-overlay/s6-rc.d/svc-machine-learning/run
- root/etc/s6-overlay/s6-rc.d/svc-server/run
- root/etc/s6-overlay/s6-rc.d/svc-typesense/run
- cleanup dependencies
- use the upstream build scripts
- cleaned up the run scripts
- expose `/import`
- probably broke something...
> tidy: cleanup image (main)

- README.md
- readme-vars.yml
The library feature is now the official way to import existing libraries. This PR updates the guide on how to import these existing libraries.
> feat: update guide to import existing library

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
Installs latest version of vips from the community edge repo until alpine 3.19 is released
> install packages from edge (noml)

- readme-vars.yml
In #197 I updated the guide in the `README.md` and not in the `readme-vars.yml` :man_facepalming:
> fix: import guide

- Dockerfile
- Dockerfile.aarch64
> feat: store geocoding dump in config folder (noml)

- Dockerfile
- Dockerfile.aarch64
> fix: revert baseimage changes (noml)

- Dockerfile
- Dockerfile.aarch64
There's issues with the migration to a base image (such as thumbnail generation for HEIC files, old JPEG format and probably more). This PR reverts the migration.
> fix: revert baseimage changes (main)

- Dockerfile
- Dockerfile.aarch64
- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
- root/etc/s6-overlay/s6-rc.d/svc-server/run
fix web build and typesense api key error
> fix: build web (noml)

- Dockerfile
- Dockerfile.aarch64
> feat: geocoding (alpine)

- Dockerfile
- Dockerfile.aarch64
> feat: geocoding (noml)

- Dockerfile
- Dockerfile.aarch64
- root/usr/local/bin/immich
This PR fixes the CLI and the arm version
> fix: cli (main)

- Dockerfile
- Dockerfile.aarch64
- root/usr/local/bin/immich
> fix: cli (noml)

- Dockerfile
- Dockerfile.aarch64
- root/usr/local/bin/immich
> fix: cli (alpine)

- readme-vars.yml
Immich recommends to use postgres 14 even if 15/16 are compatible
> fix(docs): use recommended postgres version

- Dockerfile
- Dockerfile.aarch64
> fix: v1.89 (noml)

- Dockerfile
- Dockerfile.aarch64
> fix: v1.89 (alpine)

- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
Fix possible issues with permissions on files containing geodata
> fix: permissions on geodata files (main)

- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
> fix: permissions on geodata (noml)

- Dockerfile
- Dockerfile.aarch64
Related to https://github.com/immich-app/immich/pull/5753
> fix: web root path (main)

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-test-run/run
> chore!: remove typesense (noml)

- root/usr/local/bin/immich-admin
> fix: admin cli (alpine)

- root/usr/local/bin/immich-admin
> fix: admin cli (main)

- root/usr/local/bin/immich-admin
> fix: admin cli (noml)

- Dockerfile
- Dockerfile.aarch64
> feat: move to ubuntu mantic (noml)

- Dockerfile
- readme-vars.yml
Add missing env for nvidia hardware acceleration
> fix: add missing env for nvidia (main)

- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
Stop checking folder permissions, because it can take a looooong time
> fix: stop checking folder permissions (main)

- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
> fix: stop checking folder permissions (noml)

- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
> fix: stop checking folder permissions (alpine)

- root/etc/s6-overlay/s6-rc.d/init-check-variables/run
- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
- root/etc/s6-overlay/s6-rc.d/init-test-run/run
- root/etc/s6-overlay/s6-rc.d/init-video-immich/run
- root/etc/s6-overlay/s6-rc.d/svc-machine-learning/run
- root/etc/s6-overlay/s6-rc.d/svc-microservices/run
- root/etc/s6-overlay/s6-rc.d/svc-server/run
Makes all the bash scripts shellcheck compliant
> feat: shellcheck compliant (main)

- Dockerfile
> fix: add missing env for nvidia (noml)

- root/etc/s6-overlay/s6-rc.d/init-check-variables/run
- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
- root/etc/s6-overlay/s6-rc.d/init-test-run/run
- root/etc/s6-overlay/s6-rc.d/init-video-immich/run
- root/etc/s6-overlay/s6-rc.d/svc-microservices/run
- root/etc/s6-overlay/s6-rc.d/svc-server/run
> feat: shellcheck compliant (noml)

- root/etc/s6-overlay/s6-rc.d/init-check-variables/run
- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
- root/etc/s6-overlay/s6-rc.d/svc-microservices/run
- root/etc/s6-overlay/s6-rc.d/svc-server/run
> feat: shellcheck compliant (alpine)

- Dockerfile
- Dockerfile.aarch64
- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
> fix!: v1.93 (noml)

- Dockerfile
- Dockerfile.aarch64
> fix: remove unused packages (noml)

- root/etc/s6-overlay/s6-rc.d/init-test-run/run
Upgrade pgvecto.rs from `v0.11.0` to `v.0.2.0`
> fix: v1.95 (main)

- root/etc/s6-overlay/s6-rc.d/init-test-run/run
> fix: v1.95 (noml)

- Dockerfile
- Dockerfile.aarch64
- root/usr/local/bin/immich
> fix: build CLI (noml)

- Dockerfile
- Dockerfile.aarch64
- root/usr/local/bin/immich
> fix: build CLI (alpine)

- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
> feat: apply permission to the correct media location (alpine)

- Dockerfile
- Dockerfile.aarch64
v1.102.0 has a breaking change
> fix: v1.102.0 (main)

- Dockerfile
- Dockerfile.aarch64
> fix: v1.102.0 (alpine)

- Dockerfile
- Dockerfile.aarch64
> fix: v1.102.0 (noml)

- Dockerfile
- Dockerfile.aarch64
- jenkins-vars.yml
> chore: cleanup (alpine)

- Dockerfile
- Dockerfile.aarch64
- jenkins-vars.yml
> chore: cleanup (noml)

- Dockerfile
- Dockerfile.aarch64
- jenkins-vars.yml
Cleanup the Dockerfile and [remove `donate.txt`](https://immich.app/blog/2024/immich-core-team-goes-fulltime/)
> chore: cleanup (main)

- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/svc-machine-learning/run
> feat: new env for ml (main)

- root/etc/s6-overlay/s6-rc.d/svc-machine-learning/run
> fix: ml env fallback (main)

- Dockerfile
- Dockerfile.aarch64
- root/etc/s6-overlay/s6-rc.d/svc-machine-learning/run
- root/etc/s6-overlay/s6-rc.d/svc-microservices/run
- root/etc/s6-overlay/s6-rc.d/svc-microservices/type
- root/etc/s6-overlay/s6-rc.d/svc-server/run
`v106` will introduce the ability to run microservices as a worker, this will allow running the API and microservices with a single process.
Of course, to be merged when Immich `v106` is released.
> fix: remove microservices process (main)

- Dockerfile
- Dockerfile.aarch64
- root/etc/s6-overlay/s6-rc.d/svc-microservices/run
- root/etc/s6-overlay/s6-rc.d/svc-microservices/type
- root/etc/s6-overlay/s6-rc.d/svc-server/run
> fix: remove microservices process (alpine)

- Dockerfile
- Dockerfile.aarch64
- root/etc/s6-overlay/s6-rc.d/svc-microservices/run
- root/etc/s6-overlay/s6-rc.d/svc-microservices/type
- root/etc/s6-overlay/s6-rc.d/svc-server/run
> fix: remove microservices process (noml)

- root/etc/s6-overlay/s6-rc.d/svc-microservices/run
- root/etc/s6-overlay/s6-rc.d/svc-microservices/type
- root/etc/s6-overlay/s6-rc.d/svc-server/run
> fix: use different processes for microservices and api (main)

- Dockerfile
- Dockerfile.aarch64
- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
To be merged once https://github.com/imagegenius/docker-baseimage-immich/pull/6 is merged and built
> fix: missing build-lock (main)

- Dockerfile
- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
> fix: missing build-lock (cuda)

- Dockerfile
- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
> fix: missing build lock (openvino)

- Dockerfile
- Dockerfile.aarch64
- root/etc/s6-overlay/s6-rc.d/init-config-immich/run
> fix: missing build-lock (noml)

- Dockerfile
- Dockerfile.aarch64
Can be merged now to prevent breaking changes in the next Immich release.
> refactor: build-data env (main)

- Dockerfile
- Dockerfile.aarch64
> refactor: build-data env (noml)

- Dockerfile
> refactor: build-data env (openvino)

- Dockerfile
> refactor: build-data env (cuda)

- Dockerfile
- readme-vars.yml
> refactor: import (openvino)

- Dockerfile
- readme-vars.yml
> refactor: import (cuda)

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
> refactor: import (noml)

- Dockerfile
- Dockerfile.aarch64
- readme-vars.yml
Rename `/import` by `/libraries`
> refactor: import (main)

- Dockerfile
To be merged when `v110.0` is released
> chore: update cuda

- Dockerfile
> chore: update openvino

- root/etc/s6-overlay/s6-rc.d/svc-microservices/run
- root/etc/s6-overlay/s6-rc.d/svc-server/run
> fix: breaking change (openvino)

- root/etc/s6-overlay/s6-rc.d/svc-microservices/run
- root/etc/s6-overlay/s6-rc.d/svc-server/run
> fix: breaking change (cuda)

- root/etc/s6-overlay/s6-rc.d/svc-microservices/run
- root/etc/s6-overlay/s6-rc.d/svc-server/run
> fix: breaking change (noml)

- Dockerfile
- Dockerfile.aarch64
The next immich version will ~(maybe)~ use uv instead of poetry.
> feat: immich uv (main)

- Dockerfile
> feat: immich uv (cuda)

- Dockerfile
> feat: immich uv (openvino)

- Dockerfile
- root/etc/s6-overlay/s6-rc.d/init-check-variables/run
- root/etc/s6-overlay/s6-rc.d/svc-machine-learning/run
- root/etc/s6-overlay/s6-rc.d/svc-server/run
> fix: ml breaking change (cuda)

- Dockerfile
- root/etc/s6-overlay/s6-rc.d/init-check-variables/run
- root/etc/s6-overlay/s6-rc.d/svc-machine-learning/run
- root/etc/s6-overlay/s6-rc.d/svc-server/run
> fix: ml breaking change (openvino)

- Dockerfile
- Dockerfile.aarch64
- root/etc/s6-overlay/s6-rc.d/init-check-variables/run
- root/etc/s6-overlay/s6-rc.d/svc-machine-learning/run
- root/etc/s6-overlay/s6-rc.d/svc-server/run
To be merged when the next version is released (`v1.130.4` or `v1.131.0`)
> fix: ml breaking change (main)

- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-check-variables/run
> fix: make the incorrect env obvious (main)

- root/etc/s6-overlay/s6-rc.d/init-check-variables/run
> fix: make the incorrect env obvious (noml)

- root/etc/s6-overlay/s6-rc.d/init-check-variables/run
> fix: make the incorrect env obvious (cuda)

- root/etc/s6-overlay/s6-rc.d/init-check-variables/run
> fix: make the incorrect env obvious (openvino)

- Dockerfile
> fix: remove npm link (openvino)

- Dockerfile
- Dockerfile.aarch64
> fix: remove npm link (noml)

- Dockerfile
> fix: remove npm link (cuda)

- Dockerfile
> fix: sharp install (openvino)

- Dockerfile
> fix: sharp install (cuda)

- Dockerfile
> fix: use same node version as upstream (cuda)

- Dockerfile
- Dockerfile.aarch64
- root/etc/s6-overlay/s6-rc.d/svc-server/run
> fix: use same node version as upstream (noml)

- Dockerfile
> fix: use same node version as upstream (openvino)

- readme-vars.yml
- root/etc/s6-overlay/s6-rc.d/init-test-run/run
> fix: tests with VectorChord (openvino)

- Dockerfile
- root/etc/s6-overlay/s6-rc.d/svc-microservices/run
See https://github.com/imagegenius/docker-immich/pull/592
> fix: immich v1.136.0 (cuda)
