imagegenius/docker-immich

Jenkinsfile, MIGRATION.md, jenkins-vars.yml, readme-vars.yml, root/etc/s6-overlay/s6-rc.d/init-check-variables/run
The env `JWT_SECRET` is no longer required [since January](https://github.com/immich-app/immich/pull/1383).
=> feat: remove unused `JWT_SECRET` (main)

root/etc/s6-overlay/s6-rc.d/init-check-variables/run
Immich allows to set the database parameters with `DB_HOSTNAME`, `DB_USERNAME`, `DB_PASSWORD`, `DB_DATABASE_NAME` or with only `DB_URL`. With this PR if `DB_URL` is set it does not check if  `DB_HOSTNAME` and other  envs are set.
=> fix: allow DB_URL

Dockerfile
Simplify the install for libvips dependencies. With it, we are sure to install all required dependencies, even when the base image changes.
=> fix: simplify libvips dependencies

Dockerfile, Dockerfile.aarch64
small fix following #133. It prevents to install imagemagick and libvips packages (even installed, they don't impact thumbnails generation from raw images)
=> fix: prevent to install imagemagick and libvips packages when installing libvips dependencies (main)

Dockerfile, Dockerfile.aarch64
Remove libvips-dev dependencies once imagemagick and libvips are built then install libvips dependencies. Image size is reduced by ~200MB.
=> fix: remove libvips-dev (main)

root/etc/s6-overlay/s6-rc.d/init-check-variables/run
Fix #156. `-z` returns `true` if the variable is empty...
=> fix: check if redis_socket or redis_url are set (main)

Dockerfile, Dockerfile.aarch64, root/etc/s6-overlay/s6-rc.d/svc-microservices/run, root/etc/s6-overlay/s6-rc.d/svc-server/run
Server and Microservices use mimalloc which improves [the performances](https://github.com/microsoft/mimalloc#benchmark-results-on-a-16-core-amd-5950x-zen3) like upstream images
=> feat: use libmimalloc (main)

Dockerfile, Dockerfile.aarch64
Instead of using latest versions of libvips, libraw and imagemagick, it uses now the same versions as Immich.
=> fix: use same version as immich

Dockerfile, Dockerfile.aarch64
> [!WARNING]  
> Breaking changes for v1.84.0
v1.84.0 will bring breaking changes for the machine learning install. requirements.txt won't be used anymore.
This needs to be merged after v.84.0 is out
https://github.com/immich-app/immich/pull/4700
=> fix!: machine-learning dependencies in v1.84

Dockerfile, Dockerfile.aarch64
Currently, every time a new Docker image is created, Immich downloads the reverse geocoding dump files and saves them in the /app/immich/server/.reverse-geocoding-dump directory. With this PR, Immich will download these files only once and store them in `/config/.reverse-geocoding-dump` using  the [`REVERSE_GEOCODING_DUMP_DIRECTORY`](https://immich.app/docs/install/environment-variables#geocoding) env.
=> feat: store geocoding dump in config folder (main)

Dockerfile, Dockerfile.aarch64
Currently, Immich relies on a [npm package](https://www.npmjs.com/package/local-reverse-geocoder) for retrieving city and country names based on geographical coordinates. However this package has been associated with potential crashes and excessive RAM usage. In response to these issues, there is an open PR to transition away from this package by incorporating a more stable approach (by loading the geocoding data into a PostgreSQL table). But the geocoding data is not loaded when the server starts like it's done currently with the npm package but when the image is built. 
This PR adds the geocoding data during the build, you can see here how it's done with the [Immich base image](https://github.com/immich-app/base-images/pull/15)
=> feat: geocoding (main)

Dockerfile, Dockerfile.aarch64, readme-vars.yml
Move the base image to Ubuntu mantic (23.10). Tested with raw, heic and jpeg images.
Next step, Ubuntu 24.04 LTS 😏
=> feat: move to ubuntu mantic (main)

root/etc/s6-overlay/s6-rc.d/svc-machine-learning/run
fix downloading models for a new instance #284
I tried again after a few months and it seems that now `HF_HOME` is finally being used by the machine learning process :tada:
=> fix: downloading machine learning models (main)

Dockerfile, Dockerfile.aarch64, root/etc/s6-overlay/s6-rc.d/init-config-gpu-acceleration/run
Prevent to install dev packages used by machine learning. Reduce docker image size from `2.12GB` to `2GB` (uncompressed)
=> fix: prevent installing dev packages for machine-learning (main)

Dockerfile, Dockerfile.aarch64, root/usr/local/bin/immich
In next Immich version, the CLI used to upload assets will be removed from the server dependencies. This PR builds the CLI to be sure to always have the latest CLI version (the one from the npm registry has a risk to be outdated).
This PR can be merged now.
=> fix: build CLI (main)

root/etc/s6-overlay/s6-rc.d/init-config-immich/run
If someone uses a media location other than `/photos` (can happen if you migrate from docker-compose method to the AIO).
=> feat: apply permission to the correct media location (main)

root/etc/s6-overlay/s6-rc.d/svc-microservices/run, root/etc/s6-overlay/s6-rc.d/svc-server/run
If you want to start a single worker, you have to specify which worker you want to start with an env. Until now you could start a single worker with a process arg, but that option will be removed in next version (`v1.118.0`)
Can be merged now.
=> fix: breaking change (main)

root/etc/s6-overlay/s6-rc.d/init-config-immich/run
This version https://github.com/immich-app/immich/commit/5f25e2ce824b9a7a82561a78005d36ccd2f412fa has removed the /usr/src/resources path.
=> remove IMMICH_REVERSE_GEOCODING_ROOT path

root/etc/s6-overlay/s6-rc.d/init-config-immich/run
- Added creation of new directories: `backups`, `profile`, `upload`, `thumbs`, and `encoded-video` within `${IMMICH_MEDIA_LOCATION}`.
- Ensured proper permissions are set for the new directories to maintain consistency. 
- The command
```shell
chown -R abc:abc \
"${IMMICH_MEDIA_LOCATION}" \
"${IMMICH_MEDIA_LOCATION}"/*
```
> processes ${IMMICH_MEDIA_LOCATION}/library twice. If there are many files inside, it can significantly slow down the startup process.
=> Update initialization script to create media directories

root/etc/s6-overlay/s6-rc.d/init-check-variables/run
There's no machine-learning in the noml image, no need to suggest the `MACHINE_LEARNING_* ` environment variables. And there's no port conflict, so no need for `sleep infinity`
=> fix: correct message for `IMMICH_PORT` and `IMMICH_HOST` (noml)

Dockerfile, Dockerfile.aarch64
Use automatically the same nodejs version as the one used upstream.
Merge https://github.com/imagegenius/docker-baseimage-immich/pull/17 first
=> fix: use same node version as upstream (main)
